### ISSUE TITLE
[BUG?] not building

### ISSUE THREAD

**Issue by lewislepton** [dstrekelj/odd#11]
going thru the examples, they dont build. comes up with this error message

```
lepton:Sample06 lepton$ haxe build.html5.hxml
Initialising Odd project.
/usr/local/lib/haxe/std/neko/_std/sys/FileSystem.hx:50: characters 20-55 : Invalid call
/usr/local/lib/haxe/lib/odd/git/odd/tools/macros/Utils.hx:30: characters 21-48 : Called from
/usr/local/lib/haxe/lib/odd/git/odd/tools/macros/Project.hx:18: characters 34-55 : Called from
--macro:1: character 0 : Called from
Aborted
```

**Comment by dstrekelj** [comment]
Oh my, somehow this flew completely under my radar! I know it's been a year but I'll make it a point to check what's going sometime this weekend :) I'd really like to see this work again, it's a minor miracle I managed to create it in the first place!

**Comment by dstrekelj** [comment]
Alright, Haxe 3.4.2 builds the samples fine using the git versions of the core library and target libraries. I'll give it a try with a different version.

**Comment by dstrekelj** [comment]
Ah, it seems to be v3.2.1 that was broken. I did note that 3.2.1 worked before, but I must have changed something that broke support for it. I don't think I'll go back to support it, especially since 3.4.6. is the latest version.
